kind: Pod
apiVersion: v1
metadata:
 name: labels
#  namespace: expense
 labels:
  project: expense
  component: backend
  environment: dev
spec:
  containers:
  #one pod can contains multiple containers
  - name: nginx
    image: nginx