kind: Pod
apiVersion: v1
metadata:
  name: annotations
  annotations:
    buildURL: "https://jenkins.com/expense/job/backend/23"
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  #one pod can contains multiple containers
  - name: nginx
    image: nginx