kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
  resources:
    requests:
      memory: "68Mi"
      cpu: "100m"
    linits:
        memory: "128Mi"
        cpu: "150m"
        