kind: Pod
apiVersion: v1
metadata:
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: trainer
      value: "sivakumar"
    envFrom:
    - configMapRef:
        name: configmap