kind: Service
apiVersion: v1
metadata: 
  name: nginx-lp
spec:
  type: LoadBalancer
  selector:
    project: expense
    environment: dev
    component: backend
    version: "1.0.0"  
    demo: lb
  ports:
  - protocol: TCP
    port: 80 #service port
    targetPort: 80
    NodePort: 30007
 
---

kind: Pod
apiVersion: v1
metadata:
  name: backend-lb
  labels:
    project: expense
    environment: dev
    component: backend
    version: "1.0.0" 
    demo: lb   
spec:               
  containers:
  - name: nginx
    image: nginx

